### ISSUE TITLE
git branch -r is running infinitely

### ISSUE THREAD

**Issue by shmidt** [Zollerboy1/SwiftCommand#5]
Trying to run `git branch -r` and the process never completes:

    func testGit() async throws {
        let output = try await Command.findInPath(withName: "git")!
            .setCWD("/Users/MyRepo")
                                      .addArguments(["-P", "branch", "-r"])
                                      .setStdout(.pipe)
                                      .setStderr(.pipe)
                                      .output

        print("output.stdout", output.stdout)
        print("output.stderr", output.stderr)
        XCTAssertTrue(output.status.terminatedSuccessfully)
    }

Other git commands I tried worked fine.

**Comment by Zollerboy1** [comment]
Could you provide a bit more context (e.g. which OS and version of Swift are you using)? I just added this code to my tests and it worked just fine on macOS.

**Comment by shmidt** [comment]
I need to look more into it. Probably there is an issue with my machine
