### ISSUE TITLE
Linux support in FileHandle+Async

### ISSUE THREAD

**Issue by amarcadet** [Zollerboy1/SwiftCommand#7]
Thank you for putting together this package, it helped me a lot.

However, I was wondering what is missing to fully support Linux, I can't build on Linux because of the error below.

https://github.com/Zollerboy1/SwiftCommand/blob/b4ea08c1db90532e62e1d2ea44d1c7b630b45350/Sources/SwiftCommand/FileHandle%2BAsync.swift#L12-L15

Do you have a solution or plan to fully support Linux at some point?

**Comment by Zollerboy1** [comment]
Hi,

This package should already fully support Linux. The code you linked is from an older commit and was an oversight at that time. The newest releases are all building fine on Linux for me.

Please feel free to reopen this issue if something else isn't working with the newest release of this package.

**Comment by amarcadet** [comment]
My bad you are right I was using an old version. Sorry for the inconvenience.
