### ISSUE TITLE
Call local script?

### ISSUE THREAD

**Issue by connor-ricks** [Zollerboy1/SwiftCommand#8]
Using this in my Swift command line tool, I want to call a local script `./setup.sh` but it cannot find the command. Is there a way run shell commands that are not installed in the user's bin?

**Comment by Zollerboy1** [comment]
Have you tried something like the following?

```swift
let output = await Command(executablePath: "./setup.sh").output

print(output.stdout)
```

**Comment by connor-ricks** [comment]
I'll give this a shot. I was using the find in path static method. I missed this initializer somehow when perusing source.
